{% set name = "juv" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/juv-{{ version }}.tar.gz
  sha256: bb4c133fe02f5a24b49cb360c9d8f76acbb9689761126df5686fe1dad1044bbc

build:
  noarch: python
  entry_points:
    - juv = juv:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.1.7
    - jupytext >=1.16.4
    - rich >=13.9.2
    - tomlkit >=0.13.2
    - whenever >=0.6.12
    - python-uv >=0.5.18

test:
  imports:
    - juv
  commands:
    # only do pip check with linux and osx because somehow it fails to detect tzdata even though it's clearly installed on win builds
    - pip check  # [not win]
    - juv --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/manzt/juv
  summary: A toolkit for reproducible Jupyter notebooks, powered by uv.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
